import AppKit
import Foundation

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var isPaused = false

    private let pasteboard = NSPasteboard.general
    private let maximumItemCount = ShortcutMap.labels.count
    private var lastChangeCount: Int
    private var monitorTask: Task<Void, Never>?
    private let historyURL: URL

    init() {
        lastChangeCount = pasteboard.changeCount
        historyURL = Self.makeHistoryURL()
        load()
        startMonitoring()
    }

    func togglePaused() {
        isPaused.toggle()
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        persist()
    }

    func clear() {
        items.removeAll()
        persist()
    }

    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()

        switch item.kind {
        case .text, .link:
            pasteboard.setString(item.text, forType: .string)
        case .image:
            if let data = item.imageData, let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        case .files:
            let URLs = item.filePaths.map { URL(fileURLWithPath: $0) as NSURL }
            pasteboard.writeObjects(URLs)
        }

        lastChangeCount = pasteboard.changeCount
        moveToFront(item)
    }

    private func startMonitoring() {
        monitorTask = Task { [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: .milliseconds(150))
                guard let self, !self.isPaused else { continue }
                self.capturePasteboardIfChanged()
            }
        }
    }

    private func capturePasteboardIfChanged() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        guard let item = makeClipboardItem() else { return }
        if let existingIndex = items.firstIndex(where: { $0.fingerprint == item.fingerprint }) {
            items.remove(at: existingIndex)
        }
        items.insert(item, at: 0)
        if items.count > maximumItemCount {
            items.removeLast(items.count - maximumItemCount)
        }
        persist()
    }

    private func makeClipboardItem() -> ClipboardItem? {
        let protectedTypes = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        let currentTypes = Set((pasteboard.types ?? []).map(\.rawValue))
        guard currentTypes.isDisjoint(with: protectedTypes) else { return nil }

        let sourceApplication = SourceApplication.captureFrontmost()
        let colorIndex = sourceApplication?.colorIndex ?? items.count % 10

        if let URLs = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !URLs.isEmpty {
            let paths = URLs.map(\.path)
            let names = URLs.map(\.lastPathComponent).joined(separator: "\n")
            return ClipboardItem(
                kind: .files,
                text: names,
                filePaths: paths,
                colorIndex: colorIndex,
                sourceAppName: sourceApplication?.name,
                sourceBundleIdentifier: sourceApplication?.bundleIdentifier,
                sourceIconData: sourceApplication?.iconData
            )
        }

        if pasteboard.availableType(from: [.png, .tiff]) != nil,
           let imageData = pngData(from: pasteboard) {
            let dimensions = NSImage(data: imageData)?.size
            let description = dimensions.map {
                "Image · \(Int($0.width)) × \(Int($0.height))"
            } ?? "Copied image"
            return ClipboardItem(
                kind: .image,
                text: description,
                imageData: imageData,
                colorIndex: colorIndex,
                sourceAppName: sourceApplication?.name,
                sourceBundleIdentifier: sourceApplication?.bundleIdentifier,
                sourceIconData: sourceApplication?.iconData
            )
        }

        guard let string = (pasteboard.string(forType: .URL) ?? pasteboard.string(forType: .string))?
            .trimmingCharacters(in: .whitespacesAndNewlines),
              !string.isEmpty else { return nil }

        let kind: ClipboardItem.Kind
        if let URL = URL(string: string), let scheme = URL.scheme?.lowercased(), ["http", "https"].contains(scheme) {
            kind = .link
        } else {
            kind = .text
        }

        return ClipboardItem(
            kind: kind,
            text: string,
            colorIndex: colorIndex,
            sourceAppName: sourceApplication?.name,
            sourceBundleIdentifier: sourceApplication?.bundleIdentifier,
            sourceIconData: sourceApplication?.iconData
        )
    }

    private func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let PNGData = pasteboard.data(forType: .png) {
            return PNGData
        }
        guard let TIFFData = pasteboard.data(forType: .tiff),
              let bitmap = NSBitmapImageRep(data: TIFFData) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }

    private func moveToFront(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }), index != 0 else { return }
        let existing = items.remove(at: index)
        items.insert(existing, at: 0)
        persist()
    }

    private func load() {
        guard let data = try? Data(contentsOf: historyURL),
              let decoded = try? JSONDecoder().decode([ClipboardItem].self, from: data) else { return }
        items = Array(decoded.prefix(maximumItemCount))
    }

    private func persist() {
        guard let data = try? JSONEncoder().encode(items) else { return }
        try? FileManager.default.createDirectory(
            at: historyURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try? data.write(to: historyURL, options: .atomic)
    }

    private static func makeHistoryURL() -> URL {
        let applicationSupport = FileManager.default.urls(
            for: .applicationSupportDirectory,
            in: .userDomainMask
        ).first!
        return applicationSupport
            .appendingPathComponent("ClipGrid", isDirectory: true)
            .appendingPathComponent("history.json")
    }
}
